language: cpp

# NOTE: Since we do not have direct access to either MacOS or Windows 
# machines on which to develop WE DO NOT support building on MacOS or 
# Windows. 

# For Windows, it is known that the more recent Windows 10 versions are 
# able to use either the debian archive OR AppImage (as Windows 10 now 
# allows FUSE). 

compiler: gcc

branches:
  except:  # do not build tags that we create using the upload.sh script
    - /^(?i:continuous.*)$/

jobs:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      env: CONTAINER_FROM="ubuntu:18.04"
      services:
        - docker
      addons:
        firefox: latest
      script:
      - ./buildScripts/travisLinuxDoItAll
